name: Docker

on:
  push:
    # 每次 push tag 时进行构建，不需要每次 push 都构建。使用通配符匹配每次 tag 的提交，记得 tag 名一定要以 v 开头
    branches: [ main ]
    # Publish semver tags as releases.
    tags: ['v*.*.*']


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: abulo
          password: ${{ secrets.ACCESS_TOKEN }}
      -
        name: Build and Push Latest
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: abulo/docker-golang:latest
      -
        name:  Build and Push 22.04
        uses: docker/build-push-action@v6
        with:
          file: ./22.04/Dockerfile
          push: true
          tags: abulo/docker-golang:22.04
      -
        name: Build and Push 20.04
        uses: docker/build-push-action@v6
        with:
          file: ./20.04/Dockerfile
          push: true
          tags: abulo/docker-golang:20.04
